"""Add Google OAuth support to User model

Revision ID: 151f8fc061c6
Revises: 
Create Date: 2025-08-04 11:25:28.824641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151f8fc061c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # 1. FIRST: Add google_id column
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))

        # 2. SECOND: Add auth_method as nullable initially
        batch_op.add_column(sa.Column('auth_method', sa.String(length=20), nullable=True))

        # 3. THIRD: Make password_hash nullable
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        
        # 4. FOURTH: Create unique constraint on google_id
        batch_op.create_unique_constraint(None, ['google_id'])

    # 5. FIFTH: Now update existing rows (column exists now)
    op.execute("UPDATE users SET auth_method = 'email' WHERE auth_method IS NULL")

    # 6. SIXTH: Make auth_method NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('auth_method', existing_type=sa.String(length=20), nullable=False)
        
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('auth_method')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
