"""Add Artist table and artist_id to Album

Revision ID: 193dfbde30a0
Revises: dbf5fdce85b6
Create Date: 2025-09-12 11:44:05.888161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193dfbde30a0'
down_revision = 'dbf5fdce85b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'artists', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
