"""Adding Album table, linked to Songs

Revision ID: 222110f87b83
Revises: 9616a85ff4f5
Create Date: 2025-08-30 16:53:04.884337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222110f87b83'
down_revision = '9616a85ff4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'albums', ['album_id'], ['id'])
        batch_op.drop_column('album')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('album_id')

    # ### end Alembic commands ###
