"""Add is_liked field to playlist_songs table

Revision ID: 27d6ea53cf57
Revises: 3fa53edafbd0
Create Date: 2025-08-30 12:50:30.305375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d6ea53cf57'
down_revision = '3fa53edafbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_liked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_column('is_liked')

    # ### end Alembic commands ###
