"""Add playlist_type and is_editable fields to playlists

Revision ID: 3fa53edafbd0
Revises: 512ea0392470
Create Date: 2025-08-29 16:44:24.952863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa53edafbd0'
down_revision = '512ea0392470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_type', sa.Enum('USER_CREATED', 'LIKED_SONGS', 'QUEUE', 'RECENTLY_PLAYED', 'ALBUM', 'SPOTIFY_CREATIONS', name='playlisttype'), nullable=True))
        batch_op.add_column(sa.Column('is_editable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('is_editable')
        batch_op.drop_column('playlist_type')

    # ### end Alembic commands ###
