"""Add song_count to playlists table

Revision ID: 512ea0392470
Revises: c8b6cd04d4ef
Create Date: 2025-08-28 12:21:48.596018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512ea0392470'
down_revision = 'c8b6cd04d4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('song_count')

    # ### end Alembic commands ###
