"""Adding Liked, Queue and Recently Played

Revision ID: 9616a85ff4f5
Revises: 512ea0392470
Create Date: 2025-08-30 15:54:58.140567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9616a85ff4f5'
down_revision = '512ea0392470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_column('is_liked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_liked', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
