"""Add track_number to songs table

Revision ID: c8b6cd04d4ef
Revises: 2df11efcc436
Create Date: 2025-08-27 19:05:03.661827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b6cd04d4ef'
down_revision = '2df11efcc436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('track_number')

    # ### end Alembic commands ###
